EXTRA(3lua) "3lua" "Callisto manual pages"

# NAME
*extra* - extra utility library

# SYNOPSIS
.Syn

# DESCRIPTION
The *extra* library provides utility routines
not pertaining to any other library.

Using the *csto* interpreter, these routines will be loaded into
the global environment, rather than its own library table;
therefore, these manuals will refer to *extra*'s routines
by their individual names (without the library prefix).

# SEE ALSO
callisto(3lua)
